#ifndef SPI_CONFIG_H_
#define SPI_CONFIG_H_

#define SPI_MASTER_SLAVE_SELECT			SPI_SLAVE

#define SPI_CLOCK_POLARITY				SPI_FALLING_LEADING_RISING_TRAILING

#define SPI_CLOCK_PHASE					SPI_SAMPLE_LEADING_SETUP_TRAILING


#endif /* SPI_CONFIG_H_ */
