#ifndef UART_CONFIG_H_
#define UART_CONFIG_H_

#define UART_MODE			UART_MODE_ASYNC
#define UART_PARITY	 		UART_PARITY_DISABLED
#define UART_STOPBITS		UART_STOPBITS_2
#define	UART_CHAR_SIZE		UART_CHAR_SIZE_8
#define	UART_BAUDRATE		UART_BAUDRATE_2400

#endif /* UART_CONFIG_H_ */
